# Generated by Django 3.1.4 on 2020-12-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201225_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Technology', 'Technology'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Pantry', 'Pantry'), ('Toys', 'Toys')], max_length=20),
        ),
    ]
